remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Victoria Ghielmetti's Data Analytics Portfolio
description: A place to showcase my skills.
show_downloads: true
